### ISSUE TITLE
Docker Hub Official Account?

### ISSUE THREAD

**Issue by poliveira89** [c9/templates#36]
Hello Cloud9,

I was looking around [Docker Hub](https://hub.docker.com) and found that this account:
https://hub.docker.com/u/cloud9/

Which contains some of the most pulled images with Cloud9 projects (specifically workspaces).
So made me wonder this the official (even if is not verified) account?

Thanks in advance for your reply. :+1:  Sorry to bother with such matter, but it's more comfortable if anybody on the team vouches for it.

**Comment by poliveira89** [comment]
I apologize to Cloud9 Team and particularly @fjakobs by pressuring on this matter, but I am mentioning you, because your username matches with the account name on Docker Hub that I posted before.
And I positively thought that you could give some insight on this?

**Comment by justin8** [comment]
Hey,

Yes that is the official cloud9 docker organization. I also fixed the organization name on there now :)

**Comment by poliveira89** [comment]
Thank you @justin8 and Cloud9 team, sorry to bother with such dull matter! Appreciated your comment :smile:
