### ISSUE TITLE
Bash alias for mongo init

### ISSUE THREAD

**Issue by keith24** [c9/templates#44]
I have to go to [this article](https://community.c9.io/t/setting-up-mongodb/1717) everytime I want to set up a new mongodb.  It'd be nice to have a generator in the default [`.bash_aliases`](https://github.com/c9/templates/blob/master/workspace/files/home/ubuntu/.bash_aliases): 

```
  ...
  alias mysqldump="mysqldump --user=$C9_USER --host=$IP"
  alias php="php -c ~/workspace/php.ini"
+ alias mongoinit="mkdir data && echo 'mongod --bind_ip=$IP --dbpath=data --nojournal --rest "$@"' > mongod && chmod a+x mongod"
  alias ..="cd .."
```

**Comment by bradydowling** [comment]
Most of my Mongo knowledge is limited to fragmented tutorials so bear with me. So in this scenario, you'd run `mongoinit` when you start the workspace for the first time and then from there on you would be able to run `mongod` or would you just run `mongoinit` each subsequent time as well.

**Comment by justin8** [comment]
Maybe an alias like the mysqldump and php ones above would be a little cleaner, just alias `mongod` with some sane defaults for the environment

**Comment by keith24** [comment]
@bradydowling I just copied the commands from [c9's guide to setting up mongo](https://community.c9.io/t/setting-up-mongodb/1717).  Hey, wait a minute... you wrote that guide.  So you're the mongo expert around here!  

Yes, `mongoinit` would just be for the setup, so I don't have to visit that article every time I start a new mongo project.  

@justin8 That's a good point- users are already used to typing `mongod` without the `./`.  

    alias mongod="mongod --bind_ip=$IP --dbpath=data --nojournal --rest '$@'"

But there needs to already be a directory like `data` where the db can go.  Maybe workspaces could ship with an empty `~/.mongod` folder?

**Comment by justin8** [comment]
Yeah, we can put it in ~/lib/mongod where we put apache config already.

**Comment by justin8** [comment]
I took a look at the dockerfile for workspace, and we already set up the folder and permissions for the default location /data/db, so lets leave it there so people following other tutorials or already familiar with it things find stuff where they expect it.

**Comment by keith24** [comment]
OK.  I'd think it's better to store databases outside of the workspace, so they don't get exported with the project.  (one less thing to gitignore)  But if that's how you've been doing it; better keep it that way.  

Mabye `mongod` could check for `~/workspace/data` first and create it if it doesn't exist?  My scripting isn't great so there might be a semicolon missing: 
```
mongod() {
    if [ ! -d "data" ]; then mkdir data fi
    mongod --bind_ip=$IP --dbpath=data --nojournal --rest '$@'
}
```

**Comment by justin8** [comment]
I actually made the changes already in #45. We're going to continue using the default path so that everything just works for users.

You script would be fine, but it will make a data folder wherever your current terminal is since it is not a qualified path
