### ISSUE TITLE
PHP 7 Environment

### ISSUE THREAD

**Issue by Tzaoh** [c9/templates#56]
Hello,

I would like to have the option of creating a workspace with PHP 7. I accomplished from a PHP5 environment but couldnt enable correctly xdebug mode.

I would not mind to try it and make a PR on my own but not sure how to test the config scripts.

**Comment by justin8** [comment]
This will be addressed in #49. We need a few internal changes to the runners to use the active php version via phpbrew instead of the system installed php like it currently does.

For a temporary workaround you should be able to clone the runner and modify it to use the right php version you want

**Comment by abailiss** [comment]
This will be updated in the coming days / weeks.
