### ISSUE TITLE
When will we be allowed to contribute templates again?

### ISSUE THREAD

**Issue by rogersachan** [c9/templates#71]
I'm dying to create/submit a .NET Core template, but I'm not sure if it is really wanted at this point.

**Comment by abailiss** [comment]
We currently have no plans for integrating new workspace types in the immediate future, however we are always working on improving the IDE with new features and appreciate all suggestions and feedback like this.

Keep track of updates on our blog (https://c9.io/blog) and Twitter (https://twitter.com/cloud9ide).
